// Generated by CoffeeScript 1.3.3
(function() {
  var Tribble, t1, t2;

  Tribble = (function() {

    function Tribble() {
      this.isAlive = true;
      Tribble.count++;
    }

    Tribble.prototype.breed = function() {
      if (this.isAlive) {
        return new Tribble;
      }
    };

    Tribble.prototype.die = function() {
      if (this.isAlive) {
        Tribble.count--;
      }
      return this.isAlive = false;
    };

    Tribble.count = 0;

    Tribble.makTrouble = function() {
      var i;
      return console.log(((function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this.count; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push('Trouble!');
        }
        return _results;
      }).call(this)).join(' '));
    };

    return Tribble;

  })();

  t1 = new Tribble;

  t2 = new Tribble;

  console.log(Tribble);

  console.log(Tribble.prototype);

  console.log(t1);

}).call(this);
